"""Add ref integrity

Revision ID: a4f63e5c86fb
Revises: 0676e1e7a892
Create Date: 2025-01-14 11:59:08.856736

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a4f63e5c86fb"
down_revision: Union[str, None] = "0676e1e7a892"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("booking_user_id_fkey", "booking", type_="foreignkey")
    op.drop_constraint("booking_room_id_fkey", "booking", type_="foreignkey")
    op.create_foreign_key(
        None,
        "booking",
        "user",
        ["user_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "booking",
        "room",
        ["room_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="RESTRICT",
    )
    op.alter_column(
        "room", "description", existing_type=sa.VARCHAR(), nullable=True
    )
    op.drop_constraint("room_hotel_id_fkey", "room", type_="foreignkey")
    op.create_foreign_key(
        None,
        "room",
        "hotel",
        ["hotel_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "room", type_="foreignkey")
    op.create_foreign_key(
        "room_hotel_id_fkey", "room", "hotel", ["hotel_id"], ["id"]
    )
    op.alter_column(
        "room", "description", existing_type=sa.VARCHAR(), nullable=False
    )
    op.drop_constraint(None, "booking", type_="foreignkey")
    op.drop_constraint(None, "booking", type_="foreignkey")
    op.create_foreign_key(
        "booking_room_id_fkey", "booking", "room", ["room_id"], ["id"]
    )
    op.create_foreign_key(
        "booking_user_id_fkey", "booking", "user", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###
